### ISSUE TITLE
NodeJS not displaying  over Marketplace UI

### ISSUE THREAD

**Issue by ajeetraina** [redis-developer/the-redis-marketplace-app-frontend#2]
Even if few of the apps are NodeJS based and added under the marketplace.json, it doesn't appear under "Language" section under Redis Marketplace UI.

![image](https://user-images.githubusercontent.com/313480/126435672-aec475ae-6099-40ce-aa75-077106ce8ae2.png)

**Comment by ITsolution-git** [comment]
![image](https://user-images.githubusercontent.com/24530559/135151920-cb3cc2a8-0327-47e9-bdca-6c5510b8faf2.png)
