### ISSUE TITLE
Search results with multiple parameters of the same category don't show if only one is chosed

### ISSUE THREAD

**Issue by avimredis** [redis-developer/the-redis-marketplace-app-frontend#32]
If a search result includes two parameters in the same category (e.g. Programming language Python and Javascript) the result will only appear if both are chosen.

Example: Choose CRDB, and you will see the result "Online Arcade".
If you then choose "Python", the result disappears. If you then Javascript (it uses both), the result returns. It should be able to determine AND/OR.

**Comment by ITsolution-git** [comment]
This issue is fixed as well @avimredis
